apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: warmimage-controller-admin
subjects:
  - kind: ServiceAccount
    name: warmimage-controller
    namespace: warmimage-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
