apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: warmimage-controller
  namespace: warmimage-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: warmimage-controller
    spec:
      serviceAccountName: warmimage-controller
      containers:
      - name: warmimage-controller
        image: warmimage-controller:latest
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
