package(default_visibility = ["//visibility:public"])

load("@k8s_object//:defaults.bzl", "k8s_object")

k8s_object(
    name = "authz",
    template = "authz.yaml",
)

k8s_object(
    name = "example-foo",
    template = "example-foo.yaml",
)
